nx = 50;
n4hzn = [1.5*nx, 7, 7];
tic 
mdl = n4sid(dataTrain, nx, ...
    n4sidOptions('Display','on', 'EstimateCovariance',false, ...
    'N4Weight','CVA', 'N4Horizon',n4hzn), ...
    'InputName',[], 'OutputName',string(dataTrain.Properties.VariableNames));
toc